import { useParams } from 'react-router-dom'
import HomePage from '../pages/HomePage'
import EventDetailsPage from '../pages/EventDetailsPage'

export default function CategoryRouteWrapper() {
    const { param } = useParams<{ category: string; param: string }>()

    // Logic to determine if 'param' is an event slug or a location (department/city)
    // Event slugs generated by us end with -ID (where ID starts with DT_, USER_, OED_ or is a UUID)
    // Departments are usually 2-3 chars (01, 75, 974, 2A).
    // Cities/Regions are slugs but usually don't have the specific ID pattern we use.

    const isEvent = (p: string | undefined): boolean => {
        if (!p) return false

        // Check for our specific ID patterns
        if (p.includes('-DT_') || p.includes('-USER_') || p.includes('-OED_')) {
            return true
        }

        // Fallback: if it's very long and not a known location pattern
        // Departments are short
        if (p.length <= 3) return false

        // If it starts with 'region-', it's a region (handled by specific route usually, but let's be safe)
        if (p.startsWith('region-')) return false

        return true
    }

    if (isEvent(param)) {
        return <EventDetailsPage />
    }

    return <HomePage />
}
