import { useParams } from 'react-router-dom'
import HomePage from '../pages/HomePage'
import EventDetailsPage from '../pages/EventDetailsPage'

export default function CategoryRouteWrapper() {
    const { param } = useParams<{ category: string; param: string }>()

    // Logic to determine if 'param' is an event slug or a location (department/city)
    // Event slugs generated by us end with -ID (where ID starts with DT_, USER_, OED_ or is a UUID)
    // Departments are usually 2-3 chars (01, 75, 974, 2A).
    // Cities/Regions are slugs but usually don't have the specific ID pattern we use.

    const isEvent = (p: string | undefined): boolean => {
        if (!p) return false

        // Check for our specific ID patterns
        if (p.includes('-DT_') || p.includes('-USER_') || p.includes('-OED_')) {
            return true
        }

        // Check for UUID pattern (approximate)
        // e.g. 550e8400-e29b-41d4-a716-446655440000
        if (/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}/.test(p)) {
            return true
        }

        // Default to FALSE (it's likely a city or department)
        // This fixes the issue where long city names were treated as events
        return false
    }

    if (isEvent(param)) {
        return <EventDetailsPage />
    }

    // If we are in the 2-segment route (no departmentSlug), then param is a region
    // We need to pass it as an override because HomePage expects regionSlug param
    const { departmentSlug } = useParams()

    if (!departmentSlug && param) {
        return <HomePage regionSlugOverride={param} />
    }

    return <HomePage />
}
